POST http://localhost:5500/api/item
Content-Type: application/json

{
    "item": "Tarea Ejemplo #001 en Atlas"
}

###

GET http://localhost:5500/api/items
Content-Type: application/json

###

PUT http://localhost:5500/api/item/63e6dc83a0fe7f6395c79313
Content-Type: application/json

{
    "item": "Cambia la tarea 002 por Tarea 003"
}

###

DELETE http://localhost:5500/api/item/63e6dc7ea0fe7f6395c79311
Content-Type: application/json

